services:
  k3b:
    image: ghcr.io/floristh/k3b-docker:latest
    container_name: k3b
    devices:
      - /dev/sr0:/dev/sr0
      - /dev/sg3:/dev/sg3
    cap_add:
      - SYS_RAWIO
    environment:
      - USER_ID=1000
      - GROUP_ID=1000
      - SUP_GROUP_IDS=24
      - TZ=Europe/Amsterdam
    ports:
      - '5800:5800'
    volumes:
      - /mnt/FastNAS/CDBurn/k3b-config:/config:rw
      - /mnt/FastNAS/CDBurn:/storage:rw
    restart: unless-stopped
